#!/bin/bash
# Links all the dotfiles in the home directory to this repository dotfiles.
# By default, the original dotfiles will be backed up with '*.bak' extension.
# Installs homebrew and all managed packages.

set -e
SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
SCRIPT_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

############################
# Logging
############################

# Coloring constants
__BOLD=$(tput bold)
__GREY=$(tput setaf 244)
__RED=$(tput setaf 1)
__BLUE=$(tput setaf 4)
__YELLOW=$(tput setaf 11)
__EC=$(tput sgr0)

function usage() {
  local exit_code=$1
  cat << EOF
${__BOLD}Usage${__EC}

  ${SCRIPT_NAME} [--force] [--verbose]

${__BOLD}Description${__EC}

  Links all the dotfiles in the home directory to this repository dotfiles.
  By default, the original dotfiles will be backed up with '*.bak' extension.
  Installs homebrew and all managed packages.

${__BOLD}Flags${__EC}

  -h, --help          print usage
  -f, --force         link dotfiles forcefully, without backups
  -v, --verbose       enable verbose logging

EOF
  exit "${exit_code}"
}

LOG_PREFIX=$(printf "${__GREY}dotfiles| %s|${__EC}  " "${SCRIPT_NAME}")
STDOUT_PREFIX="${LOG_PREFIX}(stdout) "
STDERR_PREFIX="${LOG_PREFIX}(stderr) "

exec 3> >(trap "" INT TERM; sed "s/^/${STDOUT_PREFIX}/" >&1)
exec 4>&1
exec 5> >(trap "" INT TERM; sed "s/^/${STDERR_PREFIX}/" >&2)
exec 6>&2

function log::enable_prefix() {
  exec 1>&3
  exec 2>&5
}

function log::disable_prefix() {
  exec 1>&4
  exec 2>&6
}

function log::error() {
  local message=$*
  printf "${LOG_PREFIX}${__RED}ERROR${__EC} %b\n" "${message}" 1>&6
}

function log::info() {
  local message=$*
  printf "${LOG_PREFIX} ${__YELLOW}INFO${__EC} %b\n" "${message}" 1>&4
}

function log::debug() {
  local message=$*
  local verbose=${VERBOSE}
  if [[ ${verbose} = true ]]; then
    printf "${LOG_PREFIX}${__BOLD}DEBUG${__EC} %b\n" "${message}" 1>&4
  fi
}

function log::fatal() {
  local message=$*
  log::error "${message}"
  exit 1
}

############################
# Input and configuration
############################

FORCE=false
VERBOSE=false

# Parse flags:
# Sadly, not using getopt quite yet: because gnu getopt is only available after setup.
while [[ $# -gt 0 ]]; do
  case $1 in
    -v|-verbose|--verbose) VERBOSE=true; shift;;
    -f|-force|--force) FORCE=true; shift;;
    -h|-help|--help) usage 0;;
    *) log::error "Unknown option: $1"; usage 1;;
  esac
done

# Settings global configurations
export VERBOSE=${VERBOSE}
export FORCE=${FORCE}

function log::header_and_config() {
  cat << EOF
  '########:::'#######::'########:'########:'####:'##:::::::'########::'######::
   ##.... ##:'##.... ##:... ##..:: ##.....::. ##:: ##::::::: ##.....::'##... ##:
   ##:::: ##: ##:::: ##:::: ##:::: ##:::::::: ##:: ##::::::: ##::::::: ##:::..::
   ##:::: ##: ##:::: ##:::: ##:::: ######:::: ##:: ##::::::: ######:::. ######::
   ##:::: ##: ##:::: ##:::: ##:::: ##...::::: ##:: ##::::::: ##...:::::..... ##:
   ##:::: ##: ##:::: ##:::: ##:::: ##:::::::: ##:: ##::::::: ##:::::::'##::: ##:
   ########::. #######::::: ##:::: ##:::::::'####: ########: ########:. ######::
  ........::::.......::::::..:::::..::::::::....::........::........:::......:::

  ${__BOLD}Setup${__EC}
  Version: $(git --no-pager log -1 --format="%H")

EOF
}

############################
# Setup
############################

log::header_and_config
log::enable_prefix

if [[ "$(uname)" != "Darwin" ]]; then
  log::fatal "Detected unsupported operating system: \"${__BOLD}$(uname)${__EC}\" (supported operating systems: MacOS)."
fi

############################
# Linking
############################

function symlink() {
  local file=$1
  local source="${SCRIPT_DIR}/${file}"
  local target="${HOME}/${file}"
  local target_backup="${HOME}/${file}.bak"
  log::info "Link source: ${SCRIPT_DIR}/${file}"
  log::info "Link target: ${HOME}/${file}"
  # Remove the backup file if exists.
  if [[ -f ${target_backup} ]] || [[ -d ${target_backup} ]] || [[ -L ${target} ]]; then
    log::debug "Removing old backup: ${target_backup}"
    log::debug rm -rf "${target_backup}"
    rm -rf "${target_backup}"
  fi

  # If the file trying to replace exist:
  # When using "--force" delete existing file or directory being linked.
  # Otherwise, move actual file to backup (e.g. .zshrc --> .zshrc.bak).
  if [[ -d ${target} ]] || [[ -f ${target} ]] || [[ -L ${target} ]]; then
      log::info exists
    if [[ ${FORCE} = true ]]; then
      log::debug rm -r "${target}"
      rm -r "${target}" || 
        log::fatal "Failed to remove target: ${target}."
    else
      log::debug "Saving backup: ${target_backup}."
      log::debug mv "${target}" "${target_backup}"
      mv "${target}" "${target_backup}" || 
        log::fatal "Failed to create backup: ${target}."
    fi
  fi

  log::debug "Creating symbolic link: ${target}"
  log::debug ln -s "${source}" "${target}"
  ln -s "${source}" "${target}" ||
    log::fatal "Failed to create symlink: ${target}."
  log::info "Created symbolic link successfully: ${target}"
}


log::info "Linking with symbolic links all the configuration files in the repository with system."
for file in * .[^.]*; do
  # Link every file in this repository excluding:
  # 1. This script.
  # 2. ".git" directory.
  # 2. ".gitmodules" directory.
  if [[ "${file}" = "${SCRIPT_NAME}" ]] || 
    [[ "${file}" = "setup" ]] || # script name is not enough in case of symlinking this script
    [[ "${file}" = ".git" ]] || 
    [[ "${file}" = ".gitmodules" ]]; then
    continue
  fi
  symlink "${file}"
done

log::info "Completed linking successfully."

############################
# Packages
############################

command -v brew &> /dev/null ||
  (log::info "Installing homebrew" &&
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
  log::info "Installed successfully.")

log::info "Updating homebrew."
log::debug brew update
brew update

HOMEBREW_PACKAGES=(
  # Programming language
  go 
  golangci-lint
  nvm # Node.js
  python

  # Usage
  ripgrep 
  neovim 
  watch
  rsync
  tmux 
  openssl
  zsh-autosuggestions
  ngrok/ngrok/ngrok
  cloudflare/cloudflare/cloudflared
  gnu-getopt

  # Git
  git
  gh
  git-delta

  # Kubernetes
  kubectl 
  kubectx
  helm
  tilt
  docker-credential-helper-ecr
  txn2/tap/kubefwd
  entr

  # Database
  libpq # Postgres
)

log::info "Installing homebrew packages: ${HOMEBREW_PACKAGES[*]}."
log::debug brew install -q "${HOMEBREW_PACKAGES[@]}"
brew install -q "${HOMEBREW_PACKAGES[@]}"
log::info "Installed successfully."

log::info "Upgrading homebrew packages."
log::debug brew upgrade
brew upgrade
log::info "Upgraded successfully."
