#!/usr/bin/env bash

set -e
SCRIPT_NAME=$(basename ${BASH_SOURCE[0]})
SCRIPT_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))


############################
# Logging
############################

# Coloring constants
__BOLD=$(tput bold)
__GREY=$(tput setaf 244)
__RED=$(tput setaf 1)
__BLUE=$(tput setaf 4)
__YELLOW=$(tput setaf 11)
__EC=$(tput sgr0)

function usage() {
  local exit_code=${EXIT_CODE}
  printf "${__BOLD}Usage${__EC}
${SCRIPT_NAME} [--force] [--verbose]

${__BOLD}Description${__EC}
  Link all the dotfiles in the home directory to this repository dotfiles.
  By default, the original dotfiles will be backed up with '*.bak' extension.

${__BOLD}Flags${__EC}
  -f, --force         Link dotfiles forcefully, without backups.
  -v, --verbose       Enable verbose logging.
"
  exit ${exit_code}
}

LOG_PREFIX=$(printf "${__GREY}dotfiles| %s|${__EC}  " "${SCRIPT_NAME}")
ERROR_TAG="${__RED}ERROR${__EC}"
ERROR_PREFIX="${LOG_PREFIX}${ERROR_TAG} "

function log::error() {
  local message=$@
  printf "%b\n" "${message}" 1>&2
}

function log::info() {
  local message=$@
  printf " ${__YELLOW}INFO${__EC} %b\n" "${message}"
}

function log::debug() {
  local message=$@
  local verbose=${VERBOSE}
  if [[ ${verbose} = true ]]; then
    printf "${__BOLD}DEBUG${__EC} %b\n" "${message}"
  fi
}

function log::fatal() {
  local message=$@
  log::error ${message}
  exit 1
}


exec 3> >(trap "" INT TERM; sed "s/^/${LOG_PREFIX}/" >&1)
exec 4>&1
exec 5> >(trap "" INT TERM; sed "s/^/${ERROR_PREFIX}/" >&2)
exec 6>&2

function log::enable_prefix() {
  exec 1>&3
  exec 2>&5
}

function log::disable_prefix() {
  exec 1>&4
  exec 2>&6
}

############################
# Input and configuration
############################

FORCE=false
VERBOSE=false

# Parse flags:
while [[ $# -gt 0 ]]; do
  case $1 in
    -v|-verbose|--verbose) VERBOSE=true; shift;;
    -f|-force|--force) FORCE=true; shift;;
    -h|-help|--help) usage; shift;;
    *) log::error "Unknown option: $1"; EXIT_CODE=1 usage;;
  esac
done

# Settings global configurations
export VERBOSE=${VERBOSE}
export FORCE=${FORCE}

function log::header_and_config() {
  printf "
  '########:::'#######::'########:'########:'####:'##:::::::'########::'######::
   ##.... ##:'##.... ##:... ##..:: ##.....::. ##:: ##::::::: ##.....::'##... ##:
   ##:::: ##: ##:::: ##:::: ##:::: ##:::::::: ##:: ##::::::: ##::::::: ##:::..::
   ##:::: ##: ##:::: ##:::: ##:::: ######:::: ##:: ##::::::: ######:::. ######::
   ##:::: ##: ##:::: ##:::: ##:::: ##...::::: ##:: ##::::::: ##...:::::..... ##:
   ##:::: ##: ##:::: ##:::: ##:::: ##:::::::: ##:: ##::::::: ##:::::::'##::: ##:
   ########::. #######::::: ##:::: ##:::::::'####: ########: ########:. ######::
  ........::::.......::::::..:::::..::::::::....::........::........:::......:::

  ${__BOLD}Setup${__EC}
  Version: $(git --no-pager log -1 --format="%H")

"
}

############################
# Setup
############################

log::header_and_config
log::enable_prefix

if [[ "$(uname)" != "Darwin" ]]; then
  log::fatal "Detected unsupported operating system: \"${__BOLD}$(uname)${__EC}\" (supported operating systems: MacOS)."
fi

############################
# Linking
############################

function symlink() {
  local file=$1
  local source="${SCRIPT_DIR}/${file}"
  local target="${HOME}/${file}"
  local target_backup="${HOME}/${file}.bak"
  log::debug "Link target: ${HOME}/${file}"
  log::debug "Link source: ${SCRIPT_DIR}/${file}"
  # Remove the backup file if exists.
  if [[ -f ${target_backup} ]] || [[ -d ${target_backup} ]]; then
    log::debug "Removing old backup: ${target_backup}"
    rm -rf ${target_backup}
  fi

  # If the file trying to replace exist:
  # When using "--force" delete existing file or directory being linked.
  # Otherwise, move actual file to backup (e.g. .zshrc --> .zshrc.bak).
  if [[ -d ${target} ]] || [[ -f ${target} ]]; then
    if [[ ${FORCE} = true ]]; then
      rm -r ${target} || 
        log::fatal "Failed to remove target: ${target}."
    else
      log::debug "Saving backup: ${target_backup}."
      mv ${target} ${target_backup} || 
        log::fatal "Failed to create backup: ${target}."
    fi
  fi

  log::debug "Creating symbolic link: ${target}"
  ln -s ${source} ${target} ||
    log::fatal "Failed to create symlink: ${target}."
}


log::info "Linking with symbolic links all the configuration files in the repository with system."
for file in * .[^.]*; do
  # Link every file in this repository excluding:
  # 1. This script.
  # 2. ".git" directory.
  # 2. ".gitmodules" directory.
  if [[ "${file}" = "${SCRIPT_NAME}" ]] || 
    [[ "${file}" = ".git" ]] || 
    [[ "${file}" = ".gitmodules" ]]; then
    continue
  fi
  symlink ${file}
done

log::info "Completed linking successfully."

############################
# Packages
############################

command -v brew &> /dev/null ||
  (log::info "Installing homebrew" &&
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
  log::info "Installed successfully.")

log::info "Updating homebrew."
brew update

HOMEBREW_PACKAGES=(
  # Programming language
  go 
  golangci-lint
  nvm # Node.js
  python

  # Usage
  ripgrep 
  neovim 
  watch
  rsync
  tmux 
  openssl
  zsh-autosuggestions

  # Git
  git
  gh

  # Kubernetes
  kubectl 
  kubectx

  # Database
  libpq # Postgres
)

log::info "Installing homebrew packages: ${HOMEBREW_PACKAGES[@]}."
brew install -q ${HOMEBREW_PACKAGES[@]}
log::info "Installed successfully."

log::info "Upgrading homebrew packages."
brew upgrade
log::info "Upgraded successfully."
