#!/usr/bin/env zsh

####################
# Script Constants #
####################

PROG_DIR=$(realpath $(dirname $0))
PROG=$(basename $0)

############
# Defaults #
############

DEFAULT_FORCE=0
DEFAULT_VERBOSE=0
DEFAULT_QUIET=0

#########
# Usage #
#########

function usage() {
  echo "Usage: ${PROG} [-fvq]"
  echo ""
  echo "Optional Flags:"
  echo "-h, --help"
  echo "-v, --verbose     (default: ${DEFAULT_VERBOSE})"
  echo "-f, --force       (default: ${DEFAULT_FORCE})"
  echo "-q, --quiet       (default: ${DEFAULT_QUIET})"
}

#########
# Flags #
#########

ARGUMENTS=()

while true; do
  [[ ${#@} -eq 0 ]] && break
  case $1 in
    --help) usage; exit 0;;
    --force) FORCE=1; shift;;
    --verbose) VERBOSE=1; shift;;
    --quiet) QUIET=1; shift;;
    --*) echo "Unknown flag: $1"; usage; exit 1;;
    -*) 
      for (( i=1; i<${#1}; i++ )); do
        c=${1:$i:1}
        case $c in
          h) usage; exit 0;;
          f) FORCE=1;;
          v) VERBOSE=1;;
          q) QUIET=1;;
          *) echo "Unknown short flag: -$c"; usage; exit 1;;
        esac
      done
      shift
      ;;
    *) ARGUMENTS=($ARGUMENTS[@] $1); shift;;
  esac
done

if [[ ${#ARGUMENTS} -ge 1 ]]; then
  usage
  exit 1
fi

FORCE=${FORCE:-$DEFAULT_FORCE}
VERBOSE=${VERBOSE:-$DEFAULT_VERBOSE}
QUIET=${QUIET:-$DEFAULT_QUIET}

#############
# Utilities #
#############

FG_RED="\033[0;31m"
FG_GREEN="\033[0;32m"
FG_BLUE="\033[0;34m"
FG_WHITE="\033[0;37m"
FG_COMMENT="\033[0;38;5;242m"

function debug() {
  (( $VERBOSE )) && echo "${FG_COMMENT}[$PROG][DBUG] ${FG_COMMENT}$@${FG_WHITE}"
}

function info() {
  echo "${FG_BLUE}[$PROG][INFO] ${FG_WHITE}$@${FG_WHITE}"
}

function error() {
  echo "${FG_RED}[$PROG][EROR] ${FG_WHITE}$@${FG_WHITE}"
}

#########
# Setup #
#########

if (( $QUIET )); then
  exec > /tmp/dotfiles
  function start_spinner() {
    spin='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
    i=0
    while true; do
      i=$(( (i+1) % ${#spin} ))
      echo -en "\r${FG_BLUE} ${spin:$i:1} ${FG_WHITE}" >&2
      sleep .05
    done
  }
  start_spinner &
  pid=$!
  function close_spinner() { 
    kill $pid 
    exit 0
  }
  trap close_spinner EXIT SIGTERM SIGINT
  exec 2>&1
fi
debug "FORCE=${FORCE}, VERBOSE=${VERBOSE}, QUIET=${QUIET}"

#################
# Installations #
#################

if [[ ! $(command -v brew) ]]; then
    info "Installing homebrew"
    debug '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else 
  info "Updating homebrew"
  debug "brew update"
  brew update
  debug "brew upgrade"
  brew upgrade
fi

if [[ ! -d $HOME/.oh-my-zsh ]]; then
  info "Installing Oh-My-Zsh"
  debug 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

formulaes=(zsh-autosuggestions)
if (( $FORCE )) || [[ ! $(command -v go) ]]; then
  formulaes=($formulaes[@] go)
fi
if (( $FORCE )) || [[ ! $(command -v nvim) ]]; then
  formulaes=($formulaes[@] neovim)
fi
if (( $FORCE )) || [[ ! $(command -v fzf) ]]; then
  formulaes=($formulaes[@] fzf)
fi
if (( $FORCE )) || [[ ! $(command -v git) ]]; then
  formulaes=($formulaes[@] git)
fi
if (( $FORCE )) || [[ ! $(command -v gh) ]]; then
  formulaes=($formulaes[@] gh)
fi
if (( $FORCE )) || [[ ! $(command -v tree) ]]; then
  formulaes=($formulaes[@] tree)
fi
if (( $FORCE )) || [[ ! $(command -v watch) ]]; then
  formulaes=($formulaes[@] watch)
fi
if (( $FORCE )) || [[ ! $(command -v rsync) ]]; then
  formulaes=($formulaes[@] coreutils)
fi
if (( $FORCE )) || [[ ! $(command -v lazygit) ]]; then
  formulaes=($formulaes[@] lazygit)
fi
if (( $FORCE )) || [[ ! -d $HOME/.nvm ]]; then
  formulaes=($formulaes[@] nvm)
fi
if (( $FORCE )) || [[ ! $(command -v rg) ]]; then
  formulaes=($formulaes[@] ripgrep)
fi

info "Installing with homebrew: ${formulaes[@]}"
debug "brew install -q $formulaes[@]"
brew install -q $formulaes[@]

if [[ ! $(command -v rustup) ]]; then
  info "Installing rust"
  debug "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
else
  info "Updating rust"
  debug "rustup update"
  rustup update
fi

if [[ ! $(command -v alacritty) ]]; then
  info "Installing alacritty"
  debug "cargo install -q alacritty"
  cargo install -q alacritty
  debug "sudo codesign --force --deep --sign - /Applications/Alacritty.app"
  sudo codesign --force --deep --sign - /Applications/Alacritty.app
else 
  info "Updating alacritty"
  debug "cargo install -q alacritty"
  cargo install -q alacritty
fi

################################################################
# Dotfiles Linking
################################################################

info "Linking the dotfiles"
DOTFILES=$(dirname $(realpath $0))

function symlink() {
  local source=$1
  local target=$2
  if (( $FORCE )) || [[ $(readlink -f $target) != $source ]]; then
    if [[ ! $FORCE -ne 0 ]] && [[ -f $target ]]; then
      vared -p "Overwrite $target? [Y/n] " -c input
    fi
    if (( $FORCE )) || [[ ${input:-y}  =~ ^(y|Y)$ ]]; then
      info "Linking ${target} -> ${source}"
      debug "rm -rf $target"
      rm -rf $target
      debug "ln -s $source $target"
      ln -s $source $target
    fi
  else
    info "Already linked ${target} -> ${source}"
  fi
}

symlink $DOTFILES/.config/nvim $HOME/.config/nvim
symlink $DOTFILES/.config/alacritty $HOME/.config/alacritty
symlink $DOTFILES/.oh-my-zsh/custom $HOME/.oh-my-zsh/custom
symlink $DOTFILES/.zshrc $HOME/.zshrc

debug "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'"
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'
exit 0
